#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter '/afs/cern.ch/work/q/querten/public/15_03_12_HSCP_Run2Preparation/CMSSW_7_4_0/src/SUSYBSMAnalysis/HSCP/test/ICHEP_Analysis/FARM/inputs/0000_HscpAnalysis.sh 0 ele'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
